name: Vue Deploy

on:
  push:
    branches:
      - master  # 触发分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build  # 需要等待构建作业完成

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # 需要创建一个 GitHub Personal Access Token，并将其存储在仓库的 secrets 中
        BRANCH: gh-pages  # 部署到 GitHub Pages 的分支
        FOLDER: dist  # 要部署的文件夹路径
